let body = document.body;
let a = document.createElement("div");
let b = document.createElement("div");
let c = document.createElement("div");
let d = document.createElement("div");
body.append(a);
body.style.display = "flex";
body.style.justifyContent = "center";
a.style.width = "800px";
a.style.height = "800px";
a.style.backgroundColor = "Indigo";
a.style.display = "flex";
a.style.justifyContent = "center";
a.style.alignItems = "center";
a.appendChild(b);
b.style.width = "600px";
b.style.height = "600px";
b.style.backgroundColor = "DarkViolet";
b.style.display = "flex";
b.style.justifyContent = "center";
b.style.alignItems = "center";
b.appendChild(c);
c.style.width = "400px";
c.style.height = "400px";
c.style.backgroundColor = "Fuchsia";
c.style.display = "flex";
c.style.justifyContent = "center";
c.style.alignItems = "center";
c.appendChild(d);
d.style.width = "100px";
d.style.height = "100px";
d.style.backgroundColor = "Purple";
d.style.display = "flex";
d.style.justifyContent = "center"
d.style.alignItems = "center";